<?xml version="1.0"?>
<robot name="mbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926"/>

    <xacro:property name="base_len" value="4.430"/>
    <xacro:property name="base_wid" value="1.74"/>
    <xacro:property name="base_hei" value="0.7"/>

    <xacro:property name="wheel_radius" value="0.35"/>
    <xacro:property name="wheel_length" value="0.11"/>
    <xacro:property name="wheel_joint_x" value="1.2"/>
    <xacro:property name="wheel_joint_y" value="0.87"/>
    <xacro:property name="wheel_joint_z" value="0.17"/>

    <xacro:property name="caster_radius" value="0.35"/>
    <xacro:property name="caster_length" value="0.11"/>

    <!-- Defining the colors used in this robot -->
    <material name="yellow">
        <color rgba="1 0.4 0 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95"/>
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>

    <!-- Macro for robot wheel -->
    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="${wheel_joint_x} ${reflect*wheel_joint_y} ${-wheel_joint_z}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
                <material name="gray" />
            </visual>
        </link>
    </xacro:macro>

    <!-- Macro for robot caster -->
    <xacro:macro name="caster" params="prefix reflect">
        <joint name="${prefix}_caster_joint" type="continuous">
            <origin xyz="-${wheel_joint_x} ${reflect*wheel_joint_y} ${-wheel_joint_z}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_caster_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length = "${caster_length}"/>
                </geometry>
                <material name="black" />
            </visual>
        </link>
    </xacro:macro>

    <xacro:macro name="mbot_base">
        <link name="base_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>
        </link>

        <joint name="base_footprint_joint" type='fixed'>
            <origin xyz="0 0 ${base_hei/2 + wheel_radius/2}" rpy="0 0 0" />        
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>

        <link name="base_link">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${base_len} ${base_wid} ${base_hei}"/>
                </geometry>
                <material name="yellow" />
            </visual>
        </link>

        <xacro:wheel prefix="base_l" reflect="-1"/>
        <xacro:wheel prefix="base_r" reflect="1"/>

        <xacro:caster prefix="left" reflect="1"/>
        <xacro:caster prefix="right" reflect="-1"/>
    </xacro:macro>
</robot>